name: mlforecast
channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - boto3
  - dask
  - lightgbm
  - numba
  - pandas
  - pip
  - pyarrow
  - pydantic
  - s3path
  - xgboost
  - pip:
    - fastcore
    - window-ops
